// <auto-generated />
using EnterpriseAiCopilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnterpriseAiCopilot.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260906120000_AddConversations")]
partial class AddConversations
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The migration operations are explicitly defined in AddConversations.cs.
        // The current model is maintained by ApplicationDbContextModelSnapshot.cs.
    }
}
