"""Application service for AI-assisted semantic-layer construction."""
import json


from src.application.dto.llm.generation_request import GenerationRequest
from src.application.dto.llm.generation_response import GenerationResponse
from src.application.dto.semantic_layer.semantic_layer_build_input import (
    SemanticLayerBuildInput,
)
from src.application.dto.semantic_layer.semantic_layer_build_response import (
    SemanticLayerBuildResponse,
)
from src.application.ports.llm_client import LLMClient
from ai.src.prompts.full_build_prompt import (
    FULL_BUILD_PROMPT,
)
from src.infrastructure.semantic_layer.builders.semantic_layer_output_parser import (
    SemanticLayerOutputParser,
)

class SemanticLayerBuilder:
    """Build an initial semantic-layer draft using an LLM.

    Input:
        SemanticLayerBuildInput containing the normalized required
        metadata and any available optional sources.

    Output:
        SemanticLayerBuildResponse containing the initial semantic-layer
        draft generated by the LLM.

    The generated draft is not validated or approved.
    Validation and human review are handled by later stages.
    """

    def __init__(self, llm_client: LLMClient) -> None:
        """Initialize the semantic-layer builder.

        Args:
            llm_client: Application-level LLM generation client.
        """
        self._llm_client = llm_client
        self._output_parser = SemanticLayerOutputParser()

    def build(self,build_input: SemanticLayerBuildInput,) -> SemanticLayerBuildResponse:
        """Generate an initial semantic-layer draft.

        Args:
            build_input: Prepared semantic-layer source data.

        Returns:
            The initial semantic-layer draft returned by the LLM.
        """
        prompt = self._build_prompt(build_input)

        request = GenerationRequest(prompt=prompt)

        response: GenerationResponse = self._llm_client.generate(request)

        semantic_layer = self._output_parser.parse(response.text)

        return SemanticLayerBuildResponse(
            semantic_layer=semantic_layer,
         )

    @staticmethod
    def _build_prompt(
        build_input: SemanticLayerBuildInput,
    ) -> str:
        """Combine the builder instructions with the provided source data.

        Args:
            build_input: Required and available optional semantic sources.

        Returns:
            Complete prompt sent to the LLM.
        """
        
        return f"""
                    {FULL_BUILD_PROMPT}

                    schema:
                    {json.dumps(build_input.schema, indent=2, ensure_ascii=False)}

                    relationships:
                    {json.dumps(build_input.relationships, indent=2, ensure_ascii=False)}

                    documentation:
                    {build_input.documentation}

                    business_glossary:
                    {build_input.business_glossary}

                    sample_data:
                    {json.dumps(build_input.sample_data, indent=2, ensure_ascii=False)}
                    """.strip()
        