from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class SemanticLayerBuildResponse:
    """Represents the initial semantic-layer draft produced by the builder.

    The response contains the raw structured output generated by the LLM.
    It is an initial draft and has not yet passed semantic validation or
    human review.

    Attributes:
        semantic_layer: Structured initial semantic-layer draft.
    """

    semantic_layer: dict[str, Any]

    def __post_init__(self) -> None:
        """Validate that the generated semantic layer is a dictionary."""
        if not isinstance(self.semantic_layer, dict):
            raise ValueError("semantic_layer must be a dictionary.")