"""Declarative prototype anchors for conversational semantic intent routing (English)."""

from __future__ import annotations

from typing import Mapping

from src.application.services.conversation.semantic_routing.domain.intent import (
    ConversationIntent,
)

# Declarative semantic prototype catalog.
# These examples serve as semantic anchors embedded once at startup.
# They are NOT exhaustive keyword lists or exact matching patterns.
DEFAULT_PROTOTYPE_CATALOG: Mapping[ConversationIntent, tuple[str, ...]] = {
    ConversationIntent.CAPABILITY: (
        "What can you do?",
        "What are you capable of?",
        "How can you help me?",
        "What is your role and what can I ask you?",
        "Explain your features and capabilities",
        "What kind of assistance do you offer?",
        "What are you?",
        "What features does the assistant support?",
        "What tasks can you perform?",
        "What types of questions can I ask?",
    ),
    ConversationIntent.LIMIT_CHANGE: (
        "Show only five",
        "Give me the top five",
        "Limit the results to ten",
        "Make it the first five records",
        "Restrict to 10 rows",
        "Just show three items",
        "Top 5 only",
        "First 10 records",
        "Limit output to 5 entries",
    ),
    ConversationIntent.SORT_CHANGE: (
        "Sort them by balance descending",
        "Order the results by revenue",
        "Sort by highest first",
        "Arrange in ascending order",
        "Order by salary from lowest to highest",
        "Sort this by date",
        "Order by amount",
        "Sort from lowest to highest",
    ),
    ConversationIntent.GROUP_BY_CHANGE: (
        "Group it by region",
        "Break down by department",
        "Group the results by category",
        "Aggregate by branch location",
        "Segment by account type",
        "Summarize by year",
        "Group the data by status",
        "Separate the records by department",
        "Separate them by category",
        "Split them by region",
        "Group by customer segment",
        "Break it down into groups",
    ),
    ConversationIntent.FILTER_CHANGE: (
        "Only Chicago",
        "Only managers",
        "What about Alexandria?",
        "What about Paris?",
        "What about smartphones?",
        "What about laptops?",
        "How about electronics?",
        "Filter by active accounts",
        "Show the same for Cairo",
        "How about in London?",
        "Same thing for Marketing",
        "What about 2024?",
        "In February",
        "Apply filter for inactive status",
        "Show the same data for another location",
        "Run the same query for New York",
    ),
    ConversationIntent.CORRECTION: (
        "No, I meant Chicago",
        "Actually, make that 2026",
        "Correction: show Alexandria instead",
        "Not Cairo, use Alexandria",
        "Actually, below 600",
        "No, change it to 2025 instead",
        "Actually, greater than 500",
        "Correction: replace with another year",
        "No, I meant last month",
        "No, change that date to 2024",
    ),
    ConversationIntent.PRONOUN_REFERENCE: (
        "Which of them has the highest balance?",
        "Who among them works in sales?",
        "Which one has the maximum amount?",
        "How many of them are active?",
        "Who is the top one among them?",
        "Which of those has the lowest score?",
        "Who among these customers has the highest revenue?",
    ),
    ConversationIntent.RESET_CONTEXT: (
        "New question",
        "Forget the previous query",
        "Start over and reset",
        "Clear conversation context",
        "Start fresh with a new question",
        "Reset the context completely",
        "Begin a new question from scratch",
    ),
    ConversationIntent.OUT_OF_SCOPE: (
        "Write a poem or a creative story",
        "Tell me a joke",
        "What is the weather outside in London?",
        "Who was the president of the United States in 1990?",
        "What is the capital of France?",
        "How tall is Mount Everest?",
        "Are you sentient, conscious, or alive?",
        "What do you think about politics?",
        "Compose a song about programming",
        "Who won the World Cup championship game?",
        "Tell me about celebrity news or sports trivia",
    ),
    ConversationIntent.NEW_DATABASE_QUERY: (
        "Show total sales by country",
        "List all active customers with their balances",
        "How many branches do we have?",
        "Display the monthly revenue report",
        "Find all transactions completed this month",
        "Select all employees in the engineering department",
        "Show overall customer count",
        "List all orders placed in 2025",
        "How many accounts were opened recently?",
        "Query total revenue across all regions",
        "Show all records from the database table",
        "Show all suppliers",
        "Show all branches",
        "Show all merchants",
        "Show all product categories",
        "Show all products",
        "List all suppliers",
        "Show customers in Alexandria",
    ),
    ConversationIntent.AMBIGUOUS: (
        "What about it?",
        "How about that?",
        "Those?",
        "Do that again",
        "Change that",
        "And that?",
    ),
}

